# Generated by Django 4.2.2 on 2023-06-23 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('version', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], max_length=100)),
                ('milage', models.CharField(validators=[django.core.validators.MinValueValidator(1)])),
                ('engine', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=250)),
                ('seat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('color', models.CharField(choices=[('read', 'Read'), ('black', 'Black')], max_length=100)),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('power', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
