# Generated by Django 4.2.2 on 2023-06-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_car_id_alter_car_milage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='new_product',
            field=models.BooleanField(default=False),
        ),
    ]
