# Generated by Django 4.2.2 on 2023-06-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_car_new_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('read', 'Read'), ('black', 'Black'), ('green', 'Green'), ('blue', 'Blue'), ('white', 'White')], max_length=100),
        ),
    ]
