# Generated by Django 4.2.2 on 2023-07-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='car_image'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='car_image'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='car_image'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='car_image'),
        ),
    ]
